### ISSUE TITLE
Slides are rendered with a different font

### ISSUE THREAD

**Issue by syoh** [kazuyanagimoto/quarto-clean-typst#1]
Thank you for this extension. It is great to be able to create PDF slides.

I need help in understanding what is happening with my setup. 

When I build the test slides, `quarto use template kazuyanagimoto/quarto-clean-typst`, I get a different font in the rendered pdf. Is this due to my setting? I am using Quarto 1.6.39 (latest as of today).

Here is a screen capture:
![image](https://github.com/user-attachments/assets/862e5c5c-8aaf-4284-b144-d2816c7ace9f)

**Comment by kazuyanagimoto** [comment]
This template's default font is Roboto. If your PC does not have it, it will be compiled with other fonts on your computer. You can download it from Google Fonts: https://fonts.google.com/specimen/Roboto. (After you download the zip file, you need to do an extra step to install it.)

I will soon support the `brand.yml`, which allows you to download Google Fonts fonts for use in Quarto documents. However, for now, you must install the fonts on your system.

**Comment by syoh** [comment]
Thanks for the explanation.

For those wanting to use Roboto font placed in `static/fonts` directory, supply an absolute path as a value to `font-paths`: i.e.,
- Instead of `font-paths: ["static/fonts"]`
- Use `font-paths: ["/absolute/path/to/static/fonts"]`
